const songs = [
      {
            title: "Supplication",
            artist: "Sami Yusuf",
            image: "/images/supplication.jpg",
            bgColor: "bg-[#9F7231]",
            textColor: "text-[#d4bb70]",
            sliderColor: "bg-[#d4bb70]",
            audioPath: "/audio/supplication.mp3",
      },
      {
            title: "Ay Khatm e Rusul Makki Madni",
            artist: "Sibtain Haider",
            image: "/images/AeKhatam-e-Rasool.jpg",
            bgColor: "bg-[#485950]",
            textColor: "text-[#c2cdc6]",
            sliderColor: "bg-[#c2cdc6]",
            audioPath: "/audio/Khatam-e-Rasool.mp3",
      },
      {
            title: "Khuda Mehshar me Puche ga",
            artist: "JSM Release",
            image: "/images/narazmathona.png",
            bgColor: "bg-[#465e87]",
            textColor: "text-[#b0cde0]",
            sliderColor: "bg-[#b0cde0]",
            audioPath: "/audio/narazmathona.mp3",
      },
      {
            title: "Tala'al Badru",
            artist: "Ayesha Abdul Basit",
            image: "/images/talaalbadru.jpg",
            bgColor: "bg-[#61444E]",
            textColor: "text-[#c4a2b2]",
            sliderColor: "bg-[#c4a2b2]",
            audioPath: "/audio/talaalbadru.mp3",
      },

      {
            title: "Ya Nabi Salam Alayka",
            artist: "Maher Zain",
            image: "/images/NabiAssalamAlyeka.jpg",
            bgColor: "bg-[#66829c]",
            textColor: "text-[#c0dae1]",
            sliderColor: "bg-[#c0dae1]",
            audioPath: "/audio/YaNabiSalamAlayka.mp3",
      },

      {
            title: "Rasool-e-Ameen",
            artist: "Junaid Jamshed",
            image: "/images/Rasool-e-Ameen.jpg",
            bgColor: "bg-[#338ea7]",
            textColor: "text-[#87cad9]",
            sliderColor: "bg-[#87cad9]",
            audioPath: "/audio/RasoolAmeen.mp3",
      },
      {
            title: "Rage",
            artist: "Pauus",
            image: "/images/rage.png",
            bgColor: "bg-[#197996]",
            textColor: "text-[#afe8f2]",
            sliderColor: "bg-[#afe8f2]",
            audioPath: "/audio/rage.mp3",
      },

      {
            title: "Machine",
            artist: "Neoni",
            image: "/images/machine.jpg",
            bgColor: "bg-[#313A7D]",
            textColor: "text-[#a4bcec]",
            sliderColor: "bg-[#a4bcec]",
            audioPath: "/audio/machine.mp3",
      },
      {
            title: "Rise Up",
            artist: "TheFatRat",
            image: "/images/rise_up.jpg",
            bgColor: "bg-[#D48947]",
            textColor: "text-[#dda56c]",
            sliderColor: "bg-[#e9c79e]",
            audioPath: "/audio/riseup.mp3",
      },
      {
            title: "Believer",
            artist: "Imagine Dragons",
            image: "/images/believer.jpg",
            bgColor: "bg-[#0abf93]",
            textColor: "text-[#7ef78c]",
            sliderColor: "bg-[#b6fcbe]",
            audioPath: "/audio/believer.mp3",
      },
      {
            title: "Sucker Punch",
            artist: "Neoni",
            image: "/images/s_punch.jpg",
            bgColor: "bg-[#BD2523]",
            textColor: "text-[#f9a9a8]",
            sliderColor: "bg-[#f9a9a8]",
            audioPath: "/audio/spunch.mp3",
      },
      {
            title: "Catatonic",
            artist: "Neoni",
            image: "/images/catatonic.jpg",
            bgColor: "bg-[#2A0001]",
            textColor: "text-[#ff5a5e]",
            sliderColor: "bg-[#ff5a5e]",
            audioPath: "/audio/catatonic.mp3",
      },
      {
            title: "Wonderland",
            artist: "Neoni",
            image: "/images/wonderland.jpg",
            bgColor: "bg-[#9D76C8]",
            textColor: "text-[#bea8dd]",
            sliderColor: "bg-[#bea8dd]",
            audioPath: "/audio/wonderland.mp3",
      },
      {
            title: "Army",
            artist: "Neoni",
            image: "/images/army.jpg",
            bgColor: "bg-[#54064C]",
            textColor: "text-[#f67cf3]",
            sliderColor: "bg-[#f67cf3]",
            audioPath: "/audio/army.mp3",
      },
      {
            title: "Peaky Blinder",
            artist: "Otnicka",
            image: "/images/peaky.png",
            bgColor: "bg-[#494949]",
            textColor: "text-[#b0b0b0]",
            sliderColor: "bg-[#b0b0b0]",
            audioPath: "/audio/peaky.mp3",
      },
];

export default songs;
